#!/usr/bin/env sh

# This script will work only on arch based distros.

echo "=============================================================================================================";
echo "                                Setup for the system will begin shortly!";
echo "=============================================================================================================";
sleep 2s;
sudo pacman -Sy --noconfirm --needed base-devel git
xrandr -r 60
sudo systemctl enable fstrim.timer
sudo systemctl enable --now bluetooth.service
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si
cd ..
rm -rf paru-bin
paru -Syu kitty fish starship linux-wifi-hotspot yt-dlp neovim brave-bin google-chrome noto-fonts-emoji nerd-fonts-source-code-pro vlc ripgrep fd exa bandwhich konsave gparted visual-studio-code-bin jdk-openjdk telegram-desktop-bin dust onlyoffice-bin flameshot;
chsh -s /bin/fish
echo "=============================================================================================================";
echo "                               Setup completed! Now enjoy with your Computer."; 
echo "=============================================================================================================";
