#!/usr/bin/env bash

# This script will work only on debian based distros.

echo "=============================================================================================================";
echo "                                Setup for the system will begin shortly!";
echo "=============================================================================================================";
sleep 3s;
sudo apt update && sudo apt upgrade -y 
sudo apt-get install neofetch
sudo apt install vim
sudo apt install git
sudo apt install make
sudo apt install gcc
sudo apt install g++
sudo apt install build-essential 
sudo apt install default-jdk
sudo apt install htop
sudo apt install wget
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
sudo snap install --classic code
sudo snap install intellij-idea-community --classic
sudo apt update && sudo apt upgrade -y
sleep 2s;
echo "=============================================================================================================";
echo "                               Setup Completed! Now enjoy with your computer."; 
echo "=============================================================================================================";
echo 
